[versions]
junit = { strictly = "[5,)", prefer = "6.0.+" }
spotless = "8.5.1"
owasp-dependencycheck = "12.2.2"

[libraries]
patch-ghsa-72hv-8253-57qq = { module = "com.fasterxml.jackson.core:jackson-core", version = { strictly = "[2.21.1,)", prefer = "2.21.1" } }

[bundles]
security-patches = ["patch-ghsa-72hv-8253-57qq"]

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owasp-dependencycheck" }
